name: ca-ui

on:
  push:

jobs:
  build-deploy:
    env:  # Keep DEPLOY_ENV as dev initially
      DEPLOY_ENV: dev
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment environment
        run: echo ${{ github.event.inputs.environment }} | tee "$HOME/deploy_env.txt"  # Store input in file
      - name: Print ca-ui
        if: ${{ steps.get_deployment_environment.outputs.is_prod }}  # Condition based on file content
        run: |
          echo "ca-ui: build production"
          # Your actual "ca-ui: build production" command goes here
      - name: Deploy to staging
        if: ${{ steps.get_deployment_environment.outputs.is_dev }}  # Condition based on file content
        run: |
          echo "ca-ui: build staging"
          # Your actual "ca-ui: build staging" command goes here